apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebrewery-frontend
  labels:
    app: codebrewery-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codebrewery-frontend
  template:
    metadata:
      labels:
        app: codebrewery-frontend
    spec:
      containers:
        - name: codebrewery-frontend
          image: slashex/codebrewery-frontend:latest
          ports:
            - containerPort: 5173  