apiVersion: v1
kind: Service
metadata:
  name: codebrewery-frontend
  labels:
    app: codebrewery-frontend
spec:
  type: ClusterIP 
  ports:
    - port: 5173  
      targetPort: 5173  
  selector:
    app: codebrewery-frontend  
