apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-service
  labels:
    app: code-execution-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: code-execution-service
  template:
    metadata:
      labels:
        app: code-execution-service
    spec:
      containers:
        - name: code-execution-service
          image: slashex/codebrewery-code-execution-service:latest  
          ports:
            - containerPort: 8081  
