apiVersion: v1
kind: Service
metadata:
  name: code-execution-service
  labels:
    app: code-execution-service
spec:
  type: ClusterIP 
  ports:
    - port: 8081  
      targetPort: 8081  
  selector:
    app: code-execution-service  
